import Header from '@/components/Header'
import '../styles/main.scss'
import type { Metadata } from 'next'
import { Baskervville } from 'next/font/google'

const inter = Baskervville({ weight:'400', subsets : ["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
